name: Lint Workflows

on:
  workflow_dispatch:
  pull_request:
    paths:
      - '.github/workflows/*.yml'
      - '.github/workflows/*.yaml'

permissions:
  contents: read

jobs:
  lint-workflows:
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
      - name: Check out repo
        uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b

      - name: Run linter
        uses: cschleiden/actions-linter@caffd707beda4fc6083926a3dff48444bc7c24aa
        with:
          # ".github/workflows/scorecards-analysis.yml" is an exception as `on: branch_protection_rule` is not recognized yet
          workflows: '[".github/workflows/*.yml", ".github/workflows/*.yaml", "!.github/workflows/scorecards-analysis.yml"]'
